import type { Metadata } from "next";
import GlobalStyles from "./styles/global";
import "./globals.css";
import ThemeProvider from "@/app/styles/themes/themeProvider";
import { getCssText } from "../../stitches.config";
import StyledComponentsRegistry from "../../lib/styled-component-registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet" />
      </head>
      <body>  
      <StyledComponentsRegistry>
        <ThemeProvider>
          <GlobalStyles />
          {children}
        </ThemeProvider>
      </StyledComponentsRegistry>
      </body>
    </html>
  );
}
