import type { Metadata } from "next";
import GlobalStyles from "./styles/global";
import "./globals.css";
import ThemeProvider from "@/app/styles/themes/themeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet" />
      </head>
      <body>
        <ThemeProvider>
          <GlobalStyles />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
