import type { Metadata } from "next";
import GlobalStyles from "./styles/global";
import "./global.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { customFonts } from "./styles/fonts"
import MuiThemeProvider from "./styles/themes/MuiThemeProvider";
import EmotionThemeProvider from "./styles/themes/EmotionThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <style />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet" />
      </head>
      <body> 
        <main className={customFonts.className}>
          <AppRouterCacheProvider>
            <MuiThemeProvider>
              <EmotionThemeProvider>
                <GlobalStyles />
                {children}
              </EmotionThemeProvider>
            </MuiThemeProvider>
          </AppRouterCacheProvider>
        </main>
      </body>
    </html>
  );
}
